name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite
  workflow_dispatch:  # Permite executar manualmente no GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gerar a cobra com base nos commits
        uses: Platane/snk@master
        with:
          github_user_name: alexandren18  # Substituí pelo seu nome de usuário
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit do arquivo gerado
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Atualizar animação da cobrinha"
          git push
